error_message = "Something went worng please try again later"
provide_phone = "Please enter your phone number"
provide_otp = "Please enter 4 digit otp"
provide_valid_otp = "Please enter valid 4 digit otp"
otp_sent_to_email = "Otp sent to your email address"
user_logged_in = "You are successfully logged in"
user_logged_out = "You are successfully logged out"
provide_correct_otp = "Please enter correct 4 digit otp"

user_data = "User data"
profile_updated = "Your profile updated successfully"
profile_created = "Profile created sucessfully"
getting_users = "Getting users list"